### ISSUE TITLE
Is this solution works with macOS 10.13.4?

### ISSUE THREAD

**Issue by jakub-zawislak** [phoenixgao/electron-high-sierra-build#2]
I just found this repo and wanted to try it out. I have macOS 10.13.4, recently updated. I tried this Electron build on the newest VS Code (1.22.1) and on an older version (1.21.1). In both versions the tabs functionality still doesn't work, there are no new options under the Window menu.

**Comment by phoenixgao** [comment]
I haven't upgraded my macOS yet, doing it now, will let you know later :p

**Comment by phoenixgao** [comment]
@jakub-zawislak I upgrade macOS to 10.13.4, and this binary works for 1.22.2 or 1.21.1

I can create new tab by pressing shift+cmd+N, and there are tab related options under window menu

could you check again?
make sure you replace the Electron binary after upgrading VS Code and restart it

**Comment by phoenixgao** [comment]
no further feedbacks and can not reproduce. feel free to reopen if anyone have this problem. close for now.

**Comment by jakub-zawislak** [comment]
I think I forgot about `"window.nativeTabs": true`. I'm so stupid 😄 I'm using VS Code on two computers and I think this option was removed over time in my config. 

Anyway, there is a new easier quick fix for native tabs - https://github.com/Microsoft/vscode/issues/35361#issuecomment-395365519
